const cases = {
  problem: { kicker: '01 / PROBLEM FRAMING', title: 'La persona no busca “un formulario”. Busca certeza.', text: 'Una empresa necesita convertir visitas en solicitudes calificadas sin pedir información innecesaria ni esconder el siguiente paso.', artifact: '<div class="artifact-title">INSIGHT MAP</div><div class="research"><div>Persona: responsable de operaciones</div><div>Fricción: no sabe qué solución necesita</div><div>Oportunidad: ofrecer diagnóstico guiado</div></div>' },
  flow: { kicker: '02 / USER FLOW', title: 'Reducir decisiones y aumentar confianza.', text: 'El flujo prioriza contexto: sector, problema, urgencia y datos mínimos para un contacto útil.', artifact: '<div class="artifact-title">USER FLOW</div><div class="flow"><span>Landing</span><b>→</b><span>Sector</span><b>→</b><span>Necesidad</span><b>→</b><span>Confirmación</span></div><div class="flow-note">Regla: cada pantalla debe responder “¿qué sigue?”</div>' },
  ui: { kicker: '03 / WIREFRAME → UI', title: 'La interfaz explica lo que pasará después.', text: 'Jerarquía visual, estados visibles y copy orientado a la acción: la persona sabe qué completar y qué recibirá.', artifact: '<div class="artifact-title">LOW-FI SCREEN</div><div class="wire"><i></i><i></i><i></i></div><div class="ui-states"><span>empty</span><span>focus</span><span>success</span></div>' },
  test: { kicker: '04 / VALIDATION', title: 'Medir no es el final: es la siguiente decisión.', text: 'Se valida con tareas breves: encontrar una solución, completar el diagnóstico y entender el mensaje de confirmación.', artifact: '<div class="artifact-title">USABILITY NOTES</div><div class="test-result"><div><strong>4/5</strong><small>completaron el flujo</small></div><div><strong>-32%</strong><small>campos innecesarios</small></div></div>' },
  strategy: { kicker: '05 / SERVICE SYSTEM', title: 'La experiencia continúa después del botón.', text: 'El diseño conecta frontend, CRM y seguimiento: la promesa que recibe la persona debe coincidir con la operación que la atiende.', artifact: '<div class="artifact-title">SERVICE BLUEPRINT</div><div class="blueprint"><span>Persona</span><span>Interfaz</span><span>CRM</span><span>Equipo</span><i></i><i></i><i></i></div>' }
};
const methods = {
  interviews: '<strong>Entrevistas</strong><span>5 conversaciones · 3 patrones repetidos</span><em>Insight: “No sé qué servicio elegir”.</em>',
  analytics: '<strong>Analítica</strong><span>GA4 · scroll depth · drop-off por campo</span><em>Señal: abandono al pedir teléfono.</em>',
  usability: '<strong>Usabilidad</strong><span>5 tareas moderadas · 1 prototipo</span><em>Resultado: completar diagnóstico en 2:41 min.</em>'
};
const order = ['problem', 'flow', 'ui', 'test', 'strategy']; const caseEl = document.querySelector('#case'); let current = localStorage.getItem('ux-blueprint-step') || 'problem';
function setupTheme() { const button = document.querySelector('#theme-toggle'); const apply = (theme) => { document.body.dataset.theme = theme; button.querySelector('.theme-label').textContent = theme === 'dark' ? 'Claro' : 'Oscuro'; button.setAttribute('aria-pressed', String(theme === 'dark')); }; apply(localStorage.getItem('portfolio-demo-theme') || 'light'); button.addEventListener('click', () => { const next = document.body.dataset.theme === 'dark' ? 'light' : 'dark'; localStorage.setItem('portfolio-demo-theme', next); apply(next); }); }
function notify(message) { const node = document.createElement('div'); node.className = 'toast'; node.textContent = message; document.body.appendChild(node); setTimeout(() => node.remove(), 1800); }
function render(key) { current = key; localStorage.setItem('ux-blueprint-step', key); const c = cases[key]; caseEl.innerHTML = `<div><span class="case-kicker">${c.kicker}</span><h2>${c.title}</h2><p>${c.text}</p></div><div class="artifact-wrap"><div class="artifact">${c.artifact}</div></div>`; document.querySelectorAll('[data-step]').forEach((button) => button.classList.toggle('active', button.dataset.step === key)); document.querySelector('#progress').textContent = `Etapa ${order.indexOf(key) + 1} de ${order.length}`; }
function exportCase() { const content = { project: 'UX Service Blueprint', currentStep: current, steps: Object.entries(cases).map(([key, value]) => ({ key, title: value.title, text: value.text })), researchMethods: Object.keys(methods) }; const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([JSON.stringify(content, null, 2)], { type: 'application/json' })); link.download = 'ux-service-blueprint.json'; link.click(); setTimeout(() => URL.revokeObjectURL(link.href), 0); notify('Caso exportado'); }
function copyText(value) { if (navigator.clipboard?.writeText) return navigator.clipboard.writeText(value); const area = document.createElement('textarea'); area.value = value; document.body.appendChild(area); area.select(); document.execCommand('copy'); area.remove(); return Promise.resolve(); }
document.querySelectorAll('[data-step]').forEach((btn) => btn.addEventListener('click', () => render(btn.dataset.step)));
document.querySelectorAll('[data-method]').forEach((btn) => btn.addEventListener('click', () => { document.querySelectorAll('[data-method]').forEach((item) => item.classList.toggle('active', item === btn)); document.querySelector('#method-output').innerHTML = methods[btn.dataset.method]; }));
document.querySelector('#export-case').addEventListener('click', exportCase); document.querySelector('#copy-brief').addEventListener('click', async () => { await copyText(`${cases[current].title}\n\n${cases[current].text}`); notify('Brief copiado'); }); document.querySelector('#reset-case').addEventListener('click', () => { render('problem'); notify('Caso reiniciado'); });
const hubLink = document.querySelector('a[href*="labs/index.html"]'); if (hubLink) hubLink.href = 'https://alinepc9128.github.io/portafolio-de-trabajo/labs/index.html';
setupTheme(); render(current); document.querySelector('#method-output').innerHTML = methods.interviews;
